In [1]:
# To create 2x3 matrix 
A <-(1:3)
B <-(4:5)


In [9]:
matrix <- rbind(A,B)
matrix

Warning message in rbind(A, B):
“number of columns of result is not a multiple of vector length (arg 2)”

[,1] [,2] [,3]
A 1    2    3   
B 4    5    4

In [3]:
# creating 3X3 matrix
mat <- matrix (1:9,nrow=3)
mat

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [8]:
# Confirming matrix
class(mat)

[1] "matrix"

In [10]:
# Creating 5x5 matrix
mat2 <- matrix (1:25, byrow=TRUE, nrow=5)
mat2

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [11]:
# Index notation to grab subsection1
mat3 <- mat2[2:3,2:3]
mat3

[,1] [,2]
[1,]  7    8  
[2,] 12   13

In [12]:
# Index notation to grab subsection2
mat4 <- mat2[4:5,4:5]
mat4

[,1] [,2]
[1,] 19   20  
[2,] 24   25

In [13]:
# Sum of elements of mat2
sum(mat2)

[1] 325

In [14]:
# runif() to create 4x5 matrix
rows=4
cols=5
mat_rand= matrix(runif(n=rows*cols), ncol=cols)
mat_rand

[,1]      [,2]      [,3]       [,4]      [,5]      
[1,] 0.9760326 0.2699019 0.05184856 0.8691574 0.09557205
[2,] 0.4367803 0.3931425 0.92895323 0.1092175 0.70620739
[3,] 0.3322790 0.1529522 0.13861702 0.2454703 0.93027479
[4,] 0.6151068 0.7617498 0.74766322 0.9628283 0.39217119